public class vaccationPackagePrice{
     public static double calculateTotalCost
             (double accommodationCost, double mealCost, double activityCost){
         return accommodationCost+mealCost+activityCost;}
    {public static void main(String[] args)
     double accommodation=input.nextDouble();
     double meal=input.nextDouble();
     double activity=input.nextDouble();
     double total=
     calculateTotalCost(double accommodationCost,double mealCost,double activitiCost);
     system.out.println("Total Vaccation Cost is:$" + total);
     }
}
